export const defaultScenario = {
  id: "adaptive-agent-mesh",
  label: "Adaptive Agent Mesh",
  agents: [
    {
      id: "orchestrator",
      label: "Orchestrator",
      initials: "OR",
      role: "coordinator",
      color: "#1f8d6a",
      reliability: 0.92,
      capabilities: ["routing", "planning", "policy"],
      position: { x: 0.5, y: 0.46 },
      summary: "Smista intenzioni, assegna responsabilita e mantiene il flusso tra gli agenti specialistici.",
      runtime: { status: "routing", load: 0.34 },
    },
    {
      id: "planner",
      label: "Planner",
      initials: "PL",
      role: "specialist",
      color: "#3d6fd8",
      reliability: 0.86,
      capabilities: ["planning", "decomposition", "handoff"],
      position: { x: 0.28, y: 0.26 },
      summary: "Scompone obiettivi grandi in task piccoli e ordinati.",
      runtime: { status: "idle", load: 0.2 },
    },
    {
      id: "scheduler",
      label: "Scheduler",
      initials: "SC",
      role: "scheduler",
      color: "#f4b647",
      reliability: 0.89,
      capabilities: ["scheduling", "calendar", "cron", "follow-up", "briefing"],
      position: { x: 0.5, y: 0.22 },
      summary: "Trasforma richieste temporali in schedule espliciti e li consegna allo scheduler runtime.",
      runtime: { status: "watching schedule", load: 0.18 },
    },
    {
      id: "researcher",
      label: "Researcher",
      initials: "RS",
      role: "specialist",
      color: "#1e9fb1",
      reliability: 0.82,
      capabilities: ["research", "retrieval", "grounding"],
      position: { x: 0.24, y: 0.68 },
      summary: "Raccoglie contesto, fonti e vincoli prima delle decisioni operative.",
      runtime: { status: "idle", load: 0.18 },
    },
    {
      id: "builder",
      label: "Builder",
      initials: "BU",
      role: "specialist",
      color: "#d8891f",
      reliability: 0.84,
      capabilities: ["implementation", "handoff", "patching"],
      position: { x: 0.72, y: 0.3 },
      summary: "Trasforma piani e contratti in modifiche concrete.",
      runtime: { status: "idle", load: 0.28 },
    },
    {
      id: "critic",
      label: "Critic",
      initials: "CR",
      role: "reviewer",
      color: "#c65050",
      reliability: 0.9,
      capabilities: ["review", "risk", "tests"],
      position: { x: 0.76, y: 0.66 },
      summary: "Valuta risultati, segnala rischi e richiede correzioni quando il protocollo lo prevede.",
      runtime: { status: "watching", load: 0.22 },
    },
    {
      id: "memory",
      label: "Memory",
      initials: "ME",
      role: "memory",
      color: "#6f56c9",
      reliability: 0.88,
      capabilities: ["memory", "context", "broadcast"],
      position: { x: 0.5, y: 0.82 },
      summary: "Mantiene stato condiviso, snapshot e decisioni gia prese.",
      runtime: { status: "synced", load: 0.24 },
    },
  ],
  relations: [
    {
      id: "orchestrator-planner",
      from: "orchestrator",
      to: "planner",
      kind: "delega",
      protocolId: "contract-net",
      latency: 0.95,
      trust: 0.9,
      bandwidth: 2,
      bidirectional: true,
    },
    {
      id: "orchestrator-researcher",
      from: "orchestrator",
      to: "researcher",
      kind: "delega",
      protocolId: "contract-net",
      latency: 1.08,
      trust: 0.84,
      bandwidth: 2,
      bidirectional: true,
    },
    {
      id: "orchestrator-scheduler",
      from: "orchestrator",
      to: "scheduler",
      kind: "schedule",
      protocolId: "schedule-control",
      latency: 0.72,
      trust: 0.9,
      bandwidth: 2,
      bidirectional: true,
    },
    {
      id: "orchestrator-builder",
      from: "orchestrator",
      to: "builder",
      kind: "delega",
      protocolId: "contract-net",
      latency: 1.12,
      trust: 0.82,
      bandwidth: 2,
      bidirectional: true,
    },
    {
      id: "planner-builder",
      from: "planner",
      to: "builder",
      kind: "handoff",
      protocolId: "contract-net",
      latency: 1.25,
      trust: 0.78,
      bandwidth: 1,
      bidirectional: true,
    },
    {
      id: "builder-critic",
      from: "builder",
      to: "critic",
      kind: "review",
      protocolId: "review-loop",
      latency: 1.2,
      trust: 0.86,
      bandwidth: 2,
      bidirectional: true,
    },
    {
      id: "orchestrator-critic",
      from: "orchestrator",
      to: "critic",
      kind: "review",
      protocolId: "review-loop",
      latency: 1.05,
      trust: 0.88,
      bandwidth: 1,
      bidirectional: true,
    },
    {
      id: "memory-orchestrator",
      from: "memory",
      to: "orchestrator",
      kind: "blackboard",
      protocolId: "blackboard-sync",
      latency: 0.7,
      trust: 0.94,
      bandwidth: 3,
      bidirectional: true,
    },
    {
      id: "memory-planner",
      from: "memory",
      to: "planner",
      kind: "blackboard",
      protocolId: "blackboard-sync",
      latency: 0.82,
      trust: 0.82,
      bandwidth: 2,
      bidirectional: true,
    },
    {
      id: "memory-researcher",
      from: "memory",
      to: "researcher",
      kind: "blackboard",
      protocolId: "blackboard-sync",
      latency: 0.9,
      trust: 0.82,
      bandwidth: 2,
      bidirectional: true,
    },
    {
      id: "memory-scheduler",
      from: "memory",
      to: "scheduler",
      kind: "blackboard",
      protocolId: "blackboard-sync",
      latency: 0.78,
      trust: 0.86,
      bandwidth: 2,
      bidirectional: true,
    },
    {
      id: "memory-builder",
      from: "memory",
      to: "builder",
      kind: "blackboard",
      protocolId: "blackboard-sync",
      latency: 0.86,
      trust: 0.8,
      bandwidth: 2,
      bidirectional: true,
    },
    {
      id: "memory-critic",
      from: "memory",
      to: "critic",
      kind: "blackboard",
      protocolId: "blackboard-sync",
      latency: 0.88,
      trust: 0.86,
      bandwidth: 2,
      bidirectional: true,
    },
  ],
  protocols: [
    {
      id: "contract-net",
      label: "Contract Net",
      color: "#1f8d6a",
      messageTypes: {
        "task.announce": {
          label: "Annuncio task",
          shortLabel: "announce",
          priority: 3,
          color: "#1f8d6a",
        },
        "task.proposal": {
          label: "Proposta",
          shortLabel: "proposal",
          priority: 2,
          color: "#3d6fd8",
        },
        "task.award": {
          label: "Assegnazione",
          shortLabel: "award",
          priority: 3,
          color: "#d8891f",
        },
        "task.status": {
          label: "Stato avanzamento",
          shortLabel: "status",
          priority: 1,
          color: "#6f56c9",
        },
      },
      rules: [
        {
          on: "task.announce",
          requiresCapability: true,
          to: "sender",
          type: "task.proposal",
          addConfidence: true,
          delay: [0.35, 1.1],
          priority: 2,
        },
        {
          on: "task.proposal",
          recipientRole: "coordinator",
          to: "sender",
          type: "task.award",
          delay: [0.25, 0.8],
          priority: 3,
        },
        {
          on: "task.award",
          to: "sender",
          type: "task.status",
          delay: [0.7, 1.8],
          priority: 1,
        },
      ],
    },
    {
      id: "blackboard-sync",
      label: "Blackboard Sync",
      color: "#6f56c9",
      messageTypes: {
        "memory.write": {
          label: "Scrittura memoria",
          shortLabel: "write",
          priority: 2,
          color: "#6f56c9",
        },
        "memory.snapshot": {
          label: "Snapshot memoria",
          shortLabel: "snapshot",
          priority: 2,
          color: "#1e9fb1",
        },
      },
      rules: [
        {
          on: "memory.write",
          recipientRole: "memory",
          to: "all-connected",
          type: "memory.snapshot",
          delay: [0.35, 0.9],
          priority: 2,
        },
      ],
    },
    {
      id: "schedule-control",
      label: "Schedule Control",
      color: "#f4b647",
      messageTypes: {
        "schedule.request": {
          label: "Richiesta schedule",
          shortLabel: "schedule",
          priority: 3,
          color: "#f4b647",
        },
        "schedule.plan": {
          label: "Piano temporale",
          shortLabel: "plan",
          priority: 3,
          color: "#facc15",
        },
        "schedule.confirm": {
          label: "Conferma runtime",
          shortLabel: "confirm",
          priority: 2,
          color: "#38bdf8",
        },
      },
      rules: [
        {
          on: "schedule.request",
          recipientRole: "scheduler",
          to: "sender",
          type: "schedule.plan",
          delay: [0.35, 0.9],
          priority: 3,
        },
        {
          on: "schedule.plan",
          recipientRole: "coordinator",
          to: "sender",
          type: "schedule.confirm",
          delay: [0.3, 0.75],
          priority: 2,
        },
      ],
    },
    {
      id: "review-loop",
      label: "Review Loop",
      color: "#c65050",
      messageTypes: {
        "review.request": {
          label: "Richiesta review",
          shortLabel: "request",
          priority: 3,
          color: "#c65050",
        },
        "review.finding": {
          label: "Finding",
          shortLabel: "finding",
          priority: 3,
          color: "#d8891f",
        },
        "review.patch": {
          label: "Patch richiesta",
          shortLabel: "patch",
          priority: 2,
          color: "#1f8d6a",
        },
      },
      rules: [
        {
          on: "review.request",
          recipientRole: "reviewer",
          to: "sender",
          type: "review.finding",
          delay: [0.6, 1.4],
          priority: 3,
        },
        {
          on: "review.finding",
          to: "sender",
          type: "review.patch",
          delay: [0.45, 1.2],
          priority: 2,
        },
      ],
    },
  ],
  intents: {
    task: {
      id: "task",
      priority: 3,
      payloads: [
        { title: "Disegna pipeline agente", capability: "planning" },
        { title: "Raccogli contesto tecnico", capability: "research" },
        { title: "Implementa modulo runtime", capability: "implementation" },
      ],
      messages: [
        {
          from: "orchestrator",
          to: "capability",
          capability: "planning",
          protocolId: "contract-net",
          type: "task.announce",
        },
        {
          from: "orchestrator",
          to: "capability",
          capability: "research",
          protocolId: "contract-net",
          type: "task.announce",
        },
        {
          from: "orchestrator",
          to: "capability",
          capability: "implementation",
          protocolId: "contract-net",
          type: "task.announce",
        },
      ],
    },
    "memory-sync": {
      id: "memory-sync",
      priority: 2,
      payloads: [
        { title: "Aggiorna contesto condiviso", capability: "memory" },
        { title: "Pubblica stato decisionale", capability: "memory" },
      ],
      messages: [
        {
          from: "orchestrator",
          to: "memory",
          protocolId: "blackboard-sync",
          type: "memory.write",
        },
      ],
    },
    schedule: {
      id: "schedule",
      priority: 3,
      payloads: [
        { title: "Programma briefing mattutino AI", capability: "scheduling" },
        { title: "Pianifica follow-up progetto", capability: "scheduling" },
      ],
      messages: [
        {
          from: "orchestrator",
          to: "scheduler",
          protocolId: "schedule-control",
          type: "schedule.request",
        },
      ],
    },
    review: {
      id: "review",
      priority: 3,
      payloads: [
        { title: "Verifica coerenza protocollo", capability: "review" },
        { title: "Controlla regressioni logiche", capability: "review" },
      ],
      messages: [
        {
          from: "builder",
          to: "critic",
          protocolId: "review-loop",
          type: "review.request",
        },
      ],
    },
  },
};
